# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SaNaay' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
  pod 'SVPinView'
  pod 'SwiftyJSON'
  #pod 'razorpay-pod'
  pod 'SVProgressHUD'
  pod 'Toast-Swift', '~> 5.0.1'
  pod "AlignedCollectionViewFlowLayout"
  pod 'AlamofireNetworkActivityLogger', '~> 2.0'
  pod 'Alamofire'
  pod 'SDWebImage'
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Messaging'
  pod 'IQKeyboardManagerSwift'
  pod 'MKMagneticProgress'
  pod 'Charts'

end


post_install do |installer|
    installer.generated_projects.each do |project|
        project.targets.each do |target|
            target.build_configurations.each do |config|
                config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
            end
        end
    end
end
